drop table if exists comments;
drop table if exists bookings;
drop table if exists items;
drop table if exists users;

create table users
(
	user_id bigint not null generated by default as identity,
	user_name varchar(255) not null,
	user_email varchar(320) not null,
	constraint users_pk primary key (user_id),
	constraint users_un unique (user_email)
);

create table items
(
	item_id bigint not null generated by default as identity,
	item_name varchar(255) not null,
	item_description varchar(255) not null,
	item_available bool not null,
	item_owner_id bigint not null,
	constraint items_pk primary key (item_id),
	constraint items_fk_owner_id foreign key (item_owner_id) references users(user_id) on delete cascade
);

create table bookings
(
    booking_id bigint not null generated by default as identity,
    booking_start timestamp without time zone not null,
    booking_end timestamp without time zone not null,
    booking_item_id bigint not null,
    booking_booker_id bigint not null,
    booking_status varchar(50) not null,
    constraint booking_pk primary key (booking_id),
    constraint booking_fk_item_id foreign key (booking_item_id) references items(item_id) on delete cascade,
    constraint booking_fk_booker_id foreign key (booking_booker_id) references users(user_id) on delete cascade
);

create table comments
(
    comment_id bigint not null generated by default as identity,
    comment_text varchar(255) not null,
    comment_item_id bigint not null,
    comment_author_id bigint not null,
    comment_created timestamp without time zone not null,
    constraint comment_pk primary key (comment_id),
    constraint comment_fk_item_id foreign key (comment_item_id) references items(item_id) on delete cascade,
    constraint comment_fk_author_id foreign key (comment_author_id) references users(user_id) on delete cascade
);